[package]
name = "crop6524"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
fast_image_resize = { version = "4.0.0", features = ["image"] }
image = "0.25.1"
